name: rllabpp
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.anaconda.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
    - kidzik
    - conda-forge
dependencies:
    - python==3.6
    - numpy==1.12.0
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.10.3
    - mako
    - ipywidgets
    - numba
    - flask
    - h5py
    - matplotlib
    - opencv3=3.1.0
    - scikit-learn
    - pytorch==0.1.9
    - mpi4py
    - pandas
    - opensim
    - lapack
    - git
    - pymongo
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - tqdm
        - msgpack-python
        - mujoco_py==0.5.7
        - cached_property
        - line_profiler
        - cloudpickle
        - Cython
        - redis
        - keras==1.2.1
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli
        - git+https://github.com/openai/gym.git@v0.7.4#egg=gym
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
        - chainer==1.18.0
        - tensorflow
        - numpy-stl==2.2.0
        - nibabel==2.1.0
        - pylru==1.0.9
        - hyperopt
        - polling
        - git+https://github.com/stanfordnmbl/osim-rl.git@ver1.5
        - psutil
